services:
  homeassistant:
    image: 'homeassistant/home-assistant:beta'
    container_name: homeassistant
    volumes:
      - .devcontainer:/config
    ports:
      - '8123:8123'
    restart: unless-stopped
