import {CONFIG_PROP} from './config-prop.const';

/**
 * These config property dependencies define config properties that
 * are dependent on the state of another config property.
 * When config is assigned in the editor, any dependent properties
 * will be cleared if their dependency is "falsy".
 */
export const CONFIG_PROP_DEPENDENCIES = {
  [CONFIG_PROP.CURRENT_TEMP_ENTITY_ID]: CONFIG_PROP.SHOW_CURRENT_TEMP,
  [CONFIG_PROP.SHOW_FEELS_LIKE_TEMP]: CONFIG_PROP.SHOW_CURRENT_TEMP,
  [CONFIG_PROP.FEELS_LIKE_TEMP_ENTITY_ID]: CONFIG_PROP.SHOW_FEELS_LIKE_TEMP,
  [CONFIG_PROP.WEATHER_ICON_ENTITY_ID]: CONFIG_PROP.SHOW_WEATHER_ICON,
  [CONFIG_PROP.USE_HA_WEATHER_ICONS]: CONFIG_PROP.SHOW_WEATHER_ICON,
  [CONFIG_PROP.TIME_ENTITY_ID]: CONFIG_PROP.SHOW_TIME,
  [CONFIG_PROP.SHOW_DATE]: CONFIG_PROP.DATE_ENTITY_ID,
  [CONFIG_PROP.DATE_ENTITY_ID]: CONFIG_PROP.SHOW_DATE,
  [CONFIG_PROP.NOW_LATER_NOW_TEMP_ENTITY_ID]: CONFIG_PROP.SHOW_NOW_LATER_TEMPS,
  [CONFIG_PROP.NOW_LATER_NOW_LABEL_ENTITY_ID]: CONFIG_PROP.SHOW_NOW_LATER_TEMPS,
  [CONFIG_PROP.NOW_LATER_LATER_TEMP_ENTITY_ID]: CONFIG_PROP.SHOW_NOW_LATER_TEMPS,
  [CONFIG_PROP.NOW_LATER_LATER_LABEL_ENTITY_ID]: CONFIG_PROP.SHOW_NOW_LATER_TEMPS,
  [CONFIG_PROP.WARNING_COUNT_ENTITY_ID]: CONFIG_PROP.SHOW_WARNING_COUNT,
  [CONFIG_PROP.HIDE_WARNING_COUNT_IF_ZERO]: CONFIG_PROP.SHOW_WARNING_COUNT,
  [CONFIG_PROP.RAIN_SUMMARY_ENTITY_ID]: CONFIG_PROP.SHOW_RAIN_SUMMARY,
  [CONFIG_PROP.FORECAST_SUMMARY_ENTITY_ID]: CONFIG_PROP.SHOW_FORECAST_SUMMARY,
  [CONFIG_PROP.DAILY_FORECAST_NUMBER_OF_DAYS]: CONFIG_PROP.SHOW_DAILY_FORECAST,
} as const;

export type CONFIG_PROP_DEPENDENCIES = typeof CONFIG_PROP_DEPENDENCIES;
export type A_CONFIG_PROP_DEPENDENCY = CONFIG_PROP_DEPENDENCIES[keyof CONFIG_PROP_DEPENDENCIES];
