import {CONFIG_PROP} from './config-prop.const';

/**
 * These are the config props that represent card entities
 */
export const CARD_ENTITIES = [
  CONFIG_PROP.SUMMARY_WEATHER_ENTITY_ID,
  CONFIG_PROP.CURRENT_TEMP_ENTITY_ID,
  CONFIG_PROP.FEELS_LIKE_TEMP_ENTITY_ID,
  CONFIG_PROP.WEATHER_ICON_ENTITY_ID,
  CONFIG_PROP.SUN_ENTITY_ID,
  CONFIG_PROP.TIME_ENTITY_ID,
  CONFIG_PROP.DATE_ENTITY_ID,
  CONFIG_PROP.NOW_LATER_NOW_TEMP_ENTITY_ID,
  CONFIG_PROP.NOW_LATER_NOW_LABEL_ENTITY_ID,
  CONFIG_PROP.NOW_LATER_LATER_TEMP_ENTITY_ID,
  CONFIG_PROP.NOW_LATER_LATER_LABEL_ENTITY_ID,
  CONFIG_PROP.WARNING_COUNT_ENTITY_ID,
  CONFIG_PROP.RAIN_SUMMARY_ENTITY_ID,
  CONFIG_PROP.FORECAST_SUMMARY_ENTITY_ID,
] as const;

export type A_CARD_ENTITY = (typeof CARD_ENTITIES)[number];
