/**
 * List of all domains in Home Assistant as of version 20250106.0
 */
export const DOMAIN: Record<string, string> = Object.freeze({
  ALERT: 'alert',
  ASSIST_SATELLITE: 'assist_satellite',
  AUTOMATION: 'automation',
  BINARY_SENSOR: 'binary_sensor',
  BUTTON: 'button',
  CALENDAR: 'calendar',
  CAMERA: 'camera',
  CLIMATE: 'climate',
  CONFIGURATOR: 'configurator',
  CONVERSATION: 'conversation',
  COVER: 'cover',
  DATE: 'date',
  DATETIME: 'datetime',
  DEVICE_TRACKER: 'device_tracker',
  EVENT: 'event',
  FAN: 'fan',
  GROUP: 'group',
  HUMIDIFIER: 'humidifier',
  IMAGE: 'image',
  INPUT_BOOLEAN: 'input_boolean',
  INPUT_BUTTON: 'input_button',
  INPUT_DATETIME: 'input_datetime',
  INPUT_NUMBER: 'input_number',
  INPUT_SELECT: 'input_select',
  INPUT_TEXT: 'input_text',
  LAWN_MOWER: 'lawn_mower',
  LIGHT: 'light',
  LOCK: 'lock',
  MEDIA_PLAYER: 'media_player',
  NUMBER: 'number',
  SCENE: 'scene',
  SCRIPT: 'script',
  SELECT: 'select',
  SENSOR: 'sensor',
  STT: 'stt',
  SWITCH: 'switch',
  TEXT: 'text',
  TIME: 'time',
  TIMER: 'timer',
  TTS: 'tts',
  UPDATE: 'update',
  VACUUM: 'vacuum',
  VALVE: 'valve',
  WATER_HEATER: 'water_heater',
  WEATHER: 'weather',
});
export type DOMAIN = typeof DOMAIN;
export type A_DOMAIN = DOMAIN[keyof DOMAIN];

export const WEATHER_DOMAINS: Array<A_DOMAIN> = [DOMAIN.WEATHER];
export const SENSOR_DOMAINS: Array<A_DOMAIN> = [DOMAIN.SENSOR];
