export const OBSERVATION_ATTRIBUTE = {
  CURRENT_TEMPERATURE: 'temperature',
};

export type OBSERVATION_ATTRIBUTE = typeof OBSERVATION_ATTRIBUTE;
export type A_OBSERVATION_ATTRIBUTE =
  OBSERVATION_ATTRIBUTE[keyof OBSERVATION_ATTRIBUTE];
