import {WEATHER_CONDITION} from './weather-conditions.const';

export const WEATHER_CONDITION_CLASSES: Record<string, string> = {
  [WEATHER_CONDITION.SUNNY]: 'clear',
  [WEATHER_CONDITION.CLEAR_NIGHT]: 'clear',
  [WEATHER_CONDITION.PARTLY_CLOUDY]: 'partly-cloudy',
  [WEATHER_CONDITION.PARTLY_CLOUDY_NIGHT]: 'partly-cloudy',
  [WEATHER_CONDITION.MOSTLY_SUNNY]: 'partly-cloudy',
  [WEATHER_CONDITION.CLOUDY]: 'cloudy',
  [WEATHER_CONDITION.LIGHTNING]: 'stormy',
  [WEATHER_CONDITION.LIGHTNING_RAINY]: 'stormy',
  [WEATHER_CONDITION.POURING]: 'rainy',
  [WEATHER_CONDITION.RAINY]: 'rainy',
  [WEATHER_CONDITION.SNOWY]: 'snowy',
  [WEATHER_CONDITION.SNOWY_RAINY]: 'snowy',
  [WEATHER_CONDITION.WINDY]: 'windy',
  [WEATHER_CONDITION.WINDY_VARIANT]: 'windy-variant',
  [WEATHER_CONDITION.FOG]: 'foggy',
  [WEATHER_CONDITION.HAIL]: 'rainy',
  [WEATHER_CONDITION.EXCEPTIONAL]: 'windy',
};
